export const PAGES = [
  'pages/home/index',
  'pages/my/index',
  // 'pages/index/index',
  'pages/web/index',
  'pages/404/index',
  // 'pages/login/index',
  // 'pages/agree/index',
  // 'pages/negotiate/index',
  // 'pages/industry_platform/index',
  // 'pages/product_group/index',
  // 'pages/product_category/index',
  'pages/product_list/index',
  'pages/product_detail/index',
  'pages/area_list/index',
]
